# Generated by Django 4.0 on 2022-08-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment2_delete_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment2',
            new_name='Comment',
        ),
    ]
